on: [push, pull_request]
name: Check All Plugins Used/Commented
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run plugins used script
        run: |
          ./_checks/plugins_used.sh
        shell: bash
