name: Update lock file
on:
  push:
  schedule:
    - cron: '0 */12 * * *'
permissions:
  contents: write
jobs:
  update-lock-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: cachix/install-nix-action@V27
        with:
            nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          ./_checks/needs_update.sh && exit 0
          nix flake update
          git config --global user.email Lumesque@users.noreply.github.com
          git config --global user.name  homemanager-config
          git add flake.lock
          git commit -am 'Automatic update'
          git push origin main
